# Generated by Django 5.2.4 on 2025-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(),
        ),
    ]
